language: android

jdk:
  - openjdk8

sudo: true

android:
  components:
    - tools
    - build-tools-28.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - android-28
    licenses:
    - ".+"

script:
  - "./gradlew clean assembleDebug"

